name: daisy_application
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

scripts:
  run: "flutter run --dart-define=DB_HOST_NAME=$DAISY_DB_HOST_NAME -t lib/pages/main.dart"

dependencies:
  flutter:
    sdk: flutter
  retrofit: "3.0.1"
  logger: any
  provider: ^6.0.3
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  ionicons: ^0.1.2
  json_serializable: "^6.2.0"
  grpc: ^3.0.2
  json_annotation: ^4.5.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.0.3
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  flutter_keyboard_visibility_web: ^2.0.0
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  fl_chart: ^0.51.0
  data_table_2: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: "^3.0.1"
  build_runner: "^2.1.11"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/intro/trending/
    - assets/icons/

  #  fonts:
  #   - family: Butler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
